# On Linux: DEPRECATED. Rust now does this by default.
# - Ubuntu, `sudo apt-get install lld clang`
# - Arch, `sudo packman -S lld clang`
# [target.x86_64-unkown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# On MacOS, `brew install llvm` and follow steps in `brew info llvm`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]
# Found that this path doesn't actually work. Not clear where the llvm bin actually is.